// Generates src/environments/environment.generated.ts from build-time env vars.
//
// This runs on `postinstall` and `prebuild` (see package.json), so the file
// always exists before a production `ng build`. The deployed backend URL is
// supplied through the TRADER_ALGO_API_BASE_URL env var (set it in the Vercel
// project settings). Local `ng serve` never needs it: the dev build replaces
// environment.ts with environment.development.ts, which points at localhost.
//
// When no env var is set the generated values are empty and the production
// environment falls back to the origin serving the app (see environment.ts).
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src', 'environments');
const outFile = join(outDir, 'environment.generated.ts');

const baseUrl = process.env.TRADER_ALGO_API_BASE_URL ?? '';
const wsUrl = process.env.TRADER_ALGO_API_WS_URL ?? '';

const contents = `// AUTO-GENERATED by scripts/generate-env.mjs at build time. Do not edit or commit.
// Values come from the TRADER_ALGO_API_BASE_URL / TRADER_ALGO_API_WS_URL env vars.
export const generatedApiConfig = {
  baseUrl: ${JSON.stringify(baseUrl)},
  wsUrl: ${JSON.stringify(wsUrl)},
};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, contents);
console.log(
  `[generate-env] wrote ${outFile} (baseUrl=${baseUrl || '<origin fallback>'})`,
);
