// Generates src/environments/environment.generated.ts from build-time config.
//
// This runs on `postinstall`, `prebuild`, and `prestart` (see package.json), so
// the file always exists before a build or dev server starts.
//
// Values are resolved in this order (first non-empty wins):
//   1. Environment variables  — how the deployed backend is configured on Vercel:
//        TRADER_ALGO_API_BASE_URL, TRADER_ALGO_API_WS_URL, TRADER_ALGO_API_KEY
//   2. .env.local.json        — a GIT-IGNORED file for local development, so the
//        localhost backend's ApiKey never gets committed to the repo.
//   3. Empty                  — the app then falls back to the serving origin for
//        URLs, and sends no API key.
//
// The API key is a secret: it lives only in the git-ignored generated file (and
// your git-ignored .env.local.json / the Vercel env var). Never hardcode it in a
// committed source file — this is a public repository.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'src', 'environments');
const outFile = join(outDir, 'environment.generated.ts');

// Optional git-ignored local overrides (development convenience only).
let local = {};
try {
  local = JSON.parse(readFileSync(join(root, '.env.local.json'), 'utf8'));
} catch {
  /* no local overrides — env vars (or empty defaults) are used */
}

const baseUrl = process.env.TRADER_ALGO_API_BASE_URL ?? local.baseUrl ?? '';
const wsUrl = process.env.TRADER_ALGO_API_WS_URL ?? local.wsUrl ?? '';
const apiKey = process.env.TRADER_ALGO_API_KEY ?? local.apiKey ?? '';

const contents = `// AUTO-GENERATED by scripts/generate-env.mjs at build time. Do not edit or commit.
// Holds the backend URL and API key sourced from env vars / .env.local.json.
export const generatedApiConfig = {
  baseUrl: ${JSON.stringify(baseUrl)},
  wsUrl: ${JSON.stringify(wsUrl)},
  apiKey: ${JSON.stringify(apiKey)},
};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, contents);
console.log(
  `[generate-env] wrote ${outFile} ` +
    `(baseUrl=${baseUrl || '<origin fallback>'}, apiKey=${apiKey ? '<set>' : '<none>'})`,
);
